import type { WorkspaceData } from "../types";
import {
  activity,
  audit,
  campaign,
  company,
  contact,
  conversation,
  deal,
  email,
  emptyData,
  form,
  inventory,
  keyword,
  meeting,
  page,
  quote,
  report,
  segment,
  sequence,
  task,
  ticket,
  user,
  workflow,
} from "./helpers";

export function seedAether(): WorkspaceData {
  const data = emptyData();

  data.users = [
    user("u_ria", "Ria Kapoor", "Head of Institutional Desk", "ria.kapoor@aethermarkets.io", "RK"),
    user("u_marcus", "Marcus Cole", "OTC Coverage", "marcus.cole@aethermarkets.io", "MC"),
    user("u_leah", "Leah Kim", "Listings & MM", "leah.kim@aethermarkets.io", "LK"),
    user("u_owen", "Owen Blake", "Compliance / Travel Rule", "owen.blake@aethermarkets.io", "OB"),
    user("u_nina", "Nina Voss", "Growth & Content", "nina.voss@aethermarkets.io", "NV"),
  ];

  data.companies = [
    company({
      id: "co_fund",
      name: "Helios Digital Capital",
      domain: "heliosdigital.com",
      type: "fund",
      industry: "Crypto fund",
      city: "Miami",
      state: "FL",
      employees: "45",
      ownerId: "u_marcus",
      lifecycle: "opportunity",
      score: 91,
      notes: "Wants $40M BTC/ETH block, T+0 settle into qualified custody.",
    }),
    company({
      id: "co_proto",
      name: "Nimbus Protocol",
      domain: "nimbus.xyz",
      type: "issuer",
      industry: "L2 / DeFi",
      city: "San Francisco",
      state: "CA",
      employees: "80",
      ownerId: "u_leah",
      lifecycle: "sql",
      score: 84,
      notes: "Listing + 6-month market-making mandate. Token not yet transferable.",
    }),
    company({
      id: "co_ex",
      name: "Harbor Exchange",
      domain: "harborex.com",
      type: "exchange",
      industry: "Centralized exchange",
      city: "Chicago",
      state: "IL",
      employees: "600",
      ownerId: "u_leah",
      lifecycle: "customer",
      score: 88,
      notes: "Listing venue. Needs MM inventory and legal memo.",
    }),
    company({
      id: "co_mm",
      name: "Vector Liquidity",
      domain: "vectorliq.io",
      type: "market_maker",
      industry: "Market making",
      city: "New York",
      state: "NY",
      employees: "120",
      ownerId: "u_leah",
      lifecycle: "customer",
      score: 93,
      notes: "Preferred MM for mid-cap listings. 25 bps spread target.",
    }),
    company({
      id: "co_family",
      name: "Ashford Family Office",
      domain: "ashfordfo.com",
      type: "fund",
      industry: "Family office",
      city: "Greenwich",
      state: "CT",
      employees: "18",
      ownerId: "u_marcus",
      lifecycle: "mql",
      score: 77,
      notes: "First BTC allocation. Education-heavy. Custody intro required.",
    }),
    company({
      id: "co_cust",
      name: "Pinnacle Qualified Custody",
      domain: "pinnacleqc.com",
      type: "partner",
      industry: "Qualified custodian",
      city: "New York",
      state: "NY",
      employees: "210",
      ownerId: "u_owen",
      lifecycle: "evangelist",
      score: 86,
      notes: "NYDFS-limited purpose trust. Standard settlement rail.",
    }),
  ];

  data.contacts = [
    contact({
      id: "ct_theo",
      firstName: "Theo",
      lastName: "Marin",
      email: "theo.marin@heliosdigital.com",
      phone: "(305) 555-0188",
      title: "Partner, Trading",
      companyId: "co_fund",
      ownerId: "u_marcus",
      lifecycle: "opportunity",
      score: 92,
      city: "Miami",
      state: "FL",
      lastActivityAt: "2026-09-07T12:10:00.000Z",
      tags: ["otc", "btc", "custody"],
    }),
    contact({
      id: "ct_ivy",
      firstName: "Ivy",
      lastName: "Chen",
      email: "ivy@nimbus.xyz",
      phone: "(415) 555-0112",
      title: "Head of BD",
      companyId: "co_proto",
      ownerId: "u_leah",
      lifecycle: "sql",
      score: 83,
      city: "San Francisco",
      state: "CA",
      lastActivityAt: "2026-09-06T19:00:00.000Z",
      tags: ["listing", "mm", "token"],
    }),
    contact({
      id: "ct_gabe",
      firstName: "Gabe",
      lastName: "Ortiz",
      email: "gortiz@harborex.com",
      phone: "(312) 555-0166",
      title: "Head of Listings",
      companyId: "co_ex",
      ownerId: "u_leah",
      lifecycle: "customer",
      score: 87,
      city: "Chicago",
      state: "IL",
      lastActivityAt: "2026-09-05T15:30:00.000Z",
      tags: ["exchange", "listings"],
    }),
    contact({
      id: "ct_mina",
      firstName: "Mina",
      lastName: "Shah",
      email: "mina@vectorliq.io",
      phone: "(212) 555-0144",
      title: "Desk Lead",
      companyId: "co_mm",
      ownerId: "u_leah",
      lifecycle: "customer",
      score: 90,
      city: "New York",
      state: "NY",
      lastActivityAt: "2026-09-07T09:40:00.000Z",
      tags: ["mm", "inventory"],
    }),
    contact({
      id: "ct_clare",
      firstName: "Clare",
      lastName: "Ashford",
      email: "clare@ashfordfo.com",
      phone: "(203) 555-0190",
      title: "CIO",
      companyId: "co_family",
      ownerId: "u_marcus",
      lifecycle: "mql",
      score: 75,
      city: "Greenwich",
      state: "CT",
      lastActivityAt: "2026-09-04T17:20:00.000Z",
      tags: ["education", "btc", "family-office"],
    }),
  ];

  data.inventory = [
    inventory({
      id: "inv_btc_block",
      name: "BTC 620 block — Helios",
      kind: "BTC / ETH block",
      sellerCompanyId: "co_fund",
      faceValue: 40_200_000,
      askingPrice: 40_200_000,
      accountCount: 1,
      avgBalance: 40_200_000,
      vintage: "spot",
      states: ["FL", "NY"],
      mediaQuality: "excellent",
      scoreBand: "n/a",
      status: "in_market",
      notes: "RFQ for 620 BTC. Prefer T+0 into Pinnacle. Two liquidity sources lined up.",
    }),
    inventory({
      id: "inv_nimb",
      name: "NIMB listing + MM",
      kind: "Token listing",
      sellerCompanyId: "co_proto",
      faceValue: 12_000_000,
      askingPrice: 850_000,
      accountCount: 1,
      avgBalance: 12_000_000,
      vintage: "TGE Q4",
      states: ["CA", "SG"],
      mediaQuality: "good",
      scoreBand: "mid-cap",
      status: "listed",
      notes: "Harbor listing application + Vector 6-month MM. Legal memo in review.",
    }),
    inventory({
      id: "inv_fo_btc",
      name: "Ashford first BTC sleeve",
      kind: "Fund allocation",
      sellerCompanyId: "co_family",
      faceValue: 5_000_000,
      askingPrice: 5_000_000,
      accountCount: 1,
      avgBalance: 5_000_000,
      vintage: "spot",
      states: ["CT"],
      mediaQuality: "fair",
      scoreBand: "n/a",
      status: "intake",
      notes: "Education + custody onboarding before any RFQ.",
    }),
    inventory({
      id: "inv_eth_mm",
      name: "ETH inventory for Harbor pairs",
      kind: "Market-making mandate",
      sellerCompanyId: "co_mm",
      faceValue: 8_400_000,
      askingPrice: 8_400_000,
      accountCount: 2,
      avgBalance: 4_200_000,
      vintage: "spot",
      states: ["NY"],
      mediaQuality: "excellent",
      scoreBand: "n/a",
      status: "awarded",
      notes: "Vector inventory live. Spread SLA 25 bps.",
    }),
  ];

  data.deals = [
    deal({
      id: "de_helios",
      name: "Helios 620 BTC block",
      companyId: "co_fund",
      contactId: "ct_theo",
      inventoryId: "inv_btc_block",
      ownerId: "u_marcus",
      stage: "Firm quote",
      amount: 40_200_000,
      closeDate: "2026-09-09",
      probability: 58,
      forecast: "best_case",
      nextStep: "Lock firm for 15 minutes once Theo confirms custody account.",
    }),
    deal({
      id: "de_nimb",
      name: "NIMB listing + MM",
      companyId: "co_proto",
      contactId: "ct_ivy",
      inventoryId: "inv_nimb",
      ownerId: "u_leah",
      stage: "Indicative",
      amount: 850_000,
      closeDate: "2026-10-15",
      probability: 42,
      forecast: "pipeline",
      nextStep: "Harbor legal + Vector term sheet in the same pack.",
    }),
    deal({
      id: "de_ash",
      name: "Ashford BTC education → custody",
      companyId: "co_family",
      contactId: "ct_clare",
      inventoryId: "inv_fo_btc",
      ownerId: "u_marcus",
      stage: "RFQ received",
      amount: 5_000_000,
      closeDate: "2026-10-30",
      probability: 22,
      forecast: "pipeline",
      nextStep: "Pinnacle intro call + IPS language.",
    }),
    deal({
      id: "de_vec",
      name: "Vector Harbor MM live",
      companyId: "co_mm",
      contactId: "ct_mina",
      inventoryId: "inv_eth_mm",
      ownerId: "u_leah",
      stage: "Post-trade",
      amount: 8_400_000,
      closeDate: "2026-08-29",
      probability: 100,
      forecast: "closed",
      nextStep: "Monthly SLA review.",
    }),
  ];

  data.activities = [
    activity({
      id: "ac_a1",
      type: "email",
      subject: "Firm window — 620 BTC",
      body: "Theo, we can show a 12bp all-in firm once Pinnacle account is live. Two liquidity sources. T+0.",
      at: "2026-09-07T12:10:00.000Z",
      userId: "u_marcus",
      contactId: "ct_theo",
      companyId: "co_fund",
      dealId: "de_helios",
    }),
    activity({
      id: "ac_a2",
      type: "meeting",
      subject: "NIMB listing working group",
      body: "Ivy, Gabe, Mina. Blockers: token transferability date and market-maker inventory wallet.",
      at: "2026-09-06T19:00:00.000Z",
      userId: "u_leah",
      contactId: "ct_ivy",
      companyId: "co_proto",
      dealId: "de_nimb",
    }),
    activity({
      id: "ac_a3",
      type: "ai",
      subject: "Travel Rule check",
      body: "Helios and Pinnacle both support IVMS-101. No blocker for ≥$3k originator data.",
      at: "2026-09-07T08:30:00.000Z",
      userId: "u_owen",
      companyId: "co_fund",
      dealId: "de_helios",
    }),
  ];

  data.tasks = [
    task({
      id: "tk_a1",
      title: "Confirm Pinnacle account for Helios",
      due: "2026-09-08",
      status: "open",
      priority: "urgent",
      ownerId: "u_marcus",
      contactId: "ct_theo",
      dealId: "de_helios",
    }),
    task({
      id: "tk_a2",
      title: "Harbor listing memo — NIMB",
      due: "2026-09-12",
      status: "open",
      priority: "high",
      ownerId: "u_leah",
      contactId: "ct_ivy",
      dealId: "de_nimb",
    }),
    task({
      id: "tk_a3",
      title: "Ashford IPS language + custody intro",
      due: "2026-09-16",
      status: "open",
      priority: "medium",
      ownerId: "u_marcus",
      contactId: "ct_clare",
      dealId: "de_ash",
    }),
  ];

  data.tickets = [
    ticket({
      id: "ti_a1",
      subject: "Travel Rule payload test — Helios → Pinnacle",
      status: "in_progress",
      priority: "high",
      requesterId: "ct_theo",
      companyId: "co_fund",
      ownerId: "u_owen",
      pipeline: "Compliance",
      createdAt: "2026-09-07T08:00:00.000Z",
      preview: "Need a $10 test with full originator/beneficiary before the 620 BTC block.",
    }),
    ticket({
      id: "ti_a2",
      subject: "Listing questionnaire incomplete — NIMB",
      status: "waiting",
      priority: "medium",
      requesterId: "ct_ivy",
      companyId: "co_proto",
      ownerId: "u_leah",
      pipeline: "Listings",
      createdAt: "2026-09-06T14:00:00.000Z",
      preview: "Missing token unlock schedule and market-maker wallet whitelist.",
    }),
  ];

  data.conversations = [
    conversation({
      id: "cv_a1",
      channel: "chat",
      subject: "620 BTC RFQ",
      contactId: "ct_theo",
      companyId: "co_fund",
      lastAt: "2026-09-07T12:12:00.000Z",
      unread: true,
      messages: [
        {
          id: "am1",
          from: "them",
          body: "Need firm on 620 BTC, T+0, Pinnacle. How long can you hold?",
          at: "2026-09-07T12:08:00.000Z",
        },
        {
          id: "am2",
          from: "us",
          body: "15-minute firm once custody account is confirmed. Indicative 12bp all-in.",
          at: "2026-09-07T12:12:00.000Z",
        },
      ],
    }),
    conversation({
      id: "cv_a2",
      channel: "email",
      subject: "Harbor listing pack",
      contactId: "ct_gabe",
      companyId: "co_ex",
      lastAt: "2026-09-05T15:30:00.000Z",
      unread: false,
      messages: [
        {
          id: "am3",
          from: "them",
          body: "Send unlock schedule and MM SLA before we slot NIMB.",
          at: "2026-09-05T15:30:00.000Z",
        },
      ],
    }),
  ];

  data.campaigns = [
    campaign({
      id: "ca_a1",
      name: "Family office BTC primer",
      type: "email",
      status: "running",
      audience: "FO CIOs — Northeast",
      sent: 320,
      opened: 141,
      clicked: 36,
      replies: 9,
      ownerId: "u_nina",
    }),
    campaign({
      id: "ca_a2",
      name: "Issuer listing office hours",
      type: "event",
      status: "scheduled",
      audience: "L2 / DeFi BD",
      sent: 80,
      opened: 0,
      clicked: 0,
      replies: 0,
      ownerId: "u_leah",
    }),
  ];

  data.emails = [
    email({
      id: "em_a1",
      name: "OTC without the group chat",
      subject: "Firm quotes, Travel Rule, qualified custody",
      status: "running",
      campaignId: "ca_a1",
      preview: "Aether Desk runs institutional blocks with documented settlement rails.",
    }),
  ];

  data.segments = [
    segment({
      id: "sg_a1",
      name: "Funds needing T+0 BTC",
      count: 11,
      definition: "Fund · tag btc · lifecycle ≥ SQL",
    }),
    segment({
      id: "sg_a2",
      name: "Issuers pre-TGE",
      count: 7,
      definition: "Issuer · inventory kind Token listing",
    }),
  ];

  data.forms = [
    form({
      id: "fo_a1",
      name: "OTC RFQ",
      submissions: 44,
      conversion: 29,
      page: "/otc",
    }),
    form({
      id: "fo_a2",
      name: "Listing application",
      submissions: 16,
      conversion: 38,
      page: "/listings",
    }),
  ];

  data.sequences = [
    sequence({
      id: "sq_a1",
      name: "FO education → custody → first block",
      steps: 6,
      enrolled: 12,
      replied: 5,
      meetings: 3,
    }),
  ];

  data.pages = [
    page({
      id: "pg_a1",
      title: "Aether Desk — institutional digital assets",
      slug: "/",
      type: "website",
      status: "published",
      views: 9200,
      updatedAt: "2026-09-02",
      excerpt: "OTC, listings, custody introductions, market-making coverage.",
    }),
    page({
      id: "pg_a2",
      title: "Request a firm quote",
      slug: "/otc",
      type: "landing",
      status: "published",
      views: 2100,
      updatedAt: "2026-09-05",
      excerpt: "BTC, ETH, and liquid alts. Travel Rule native.",
    }),
    page({
      id: "pg_a3",
      title: "How desks settle T+0 into qualified custody",
      slug: "/blog/tplus0-custody",
      type: "blog",
      status: "published",
      views: 3400,
      updatedAt: "2026-08-18",
      excerpt: "IVMS-101, prefunded inventory, and why 15-minute firms exist.",
    }),
  ];

  data.keywords = [
    keyword({
      id: "kw_a1",
      term: "institutional bitcoin otc desk",
      volume: 540,
      position: 5,
      difficulty: 48,
      url: "/otc",
      intent: "transactional",
    }),
    keyword({
      id: "kw_a2",
      term: "crypto token listing market maker",
      volume: 310,
      position: 9,
      difficulty: 41,
      url: "/listings",
      intent: "commercial",
    }),
    keyword({
      id: "kw_a3",
      term: "qualified custody bitcoin family office",
      volume: 260,
      position: 7,
      difficulty: 34,
      url: "/blog/tplus0-custody",
      intent: "informational",
    }),
  ];

  data.audits = [
    audit({
      id: "au_a1",
      severity: "medium",
      title: "OTC landing missing comparison table",
      page: "/otc",
      recommendation: "Add RFQ vs RFQ-firm vs streaming for AEO/SEO.",
    }),
  ];

  data.workflows = [
    workflow({
      id: "wf_a1",
      name: "OTC RFQ → coverage + compliance",
      status: "active",
      trigger: "Form submitted: OTC RFQ",
      enrolled: 44,
      goal: "Create deal in RFQ received, ping Marcus, Travel Rule ticket if ≥ $3k",
    }),
    workflow({
      id: "wf_a2",
      name: "Listing pack complete → Harbor",
      status: "active",
      trigger: "Unlock schedule + MM wallet uploaded",
      enrolled: 6,
      goal: "Advance to Indicative and email Gabe",
    }),
  ];

  data.reports = [
    report({
      id: "rp_a1",
      name: "Desk notional — Sep",
      hub: "sales",
      insight: "$54M open notional. Helios is the week’s swing trade.",
    }),
    report({
      id: "rp_a2",
      name: "Listing funnel",
      hub: "marketplace",
      insight: "3 issuers stuck on unlock schedules.",
    }),
  ];

  data.quotes = [
    quote({
      id: "qt_a1",
      dealId: "de_helios",
      name: "Indicative 12bp — 620 BTC",
      amount: 40_200_000,
      status: "sent",
    }),
  ];

  data.meetings = [
    meeting({
      id: "mt_a1",
      title: "Helios firm window",
      when: "2026-09-08T15:00:00.000Z",
      contactId: "ct_theo",
      dealId: "de_helios",
      location: "Signal + recorded line",
    }),
  ];

  data.aiMessages = [
    {
      id: "ai_a0",
      role: "assistant",
      body: "I'm Meridian AI for Aether Desk. I can draft RFQs, check Travel Rule readiness, summarize listing blockers, and keep custody language precise. Ask about the Helios 620 BTC block.",
      at: "2026-09-07T08:00:00.000Z",
    },
  ];

  return data;
}
