import type { WorkspaceData } from "../types";
import {
  activity,
  audit,
  campaign,
  company,
  contact,
  conversation,
  deal,
  email,
  emptyData,
  form,
  inventory,
  keyword,
  meeting,
  page,
  quote,
  report,
  segment,
  sequence,
  task,
  ticket,
  user,
  workflow,
} from "./helpers";

export function seedTriton(): WorkspaceData {
  const data = emptyData();

  data.users = [
    user("u_alex", "Alex Chen", "Managing Director, Brokerage", "alex.chen@debtmarket.net", "AC"),
    user("u_maya", "Maya Ortiz", "Head of Seller Coverage", "maya.ortiz@debtmarket.net", "MO"),
    user("u_jordan", "Jordan Hale", "Buyer Desk Lead", "jordan.hale@debtmarket.net", "JH"),
    user("u_priya", "Priya Shah", "Compliance Counsel", "priya.shah@debtmarket.net", "PS"),
    user("u_noah", "Noah Bennett", "Marketing & CMS", "noah.bennett@debtmarket.net", "NB"),
  ];

  data.companies = [
    company({
      id: "co_fhb",
      name: "First Horizon Bank",
      domain: "firsthorizon.com",
      type: "seller",
      industry: "Regional bank",
      city: "Memphis",
      state: "TN",
      employees: "5,000+",
      ownerId: "u_maya",
      lifecycle: "opportunity",
      score: 92,
      notes: "Recurring Q3 credit-card charge-off seller. Prefers 21-day bid windows.",
    }),
    company({
      id: "co_navy",
      name: "Atlantic Coast Credit Union",
      domain: "atlanticcoastcu.org",
      type: "seller",
      industry: "Credit union",
      city: "Jacksonville",
      state: "FL",
      employees: "800",
      ownerId: "u_maya",
      lifecycle: "sql",
      score: 81,
      notes: "First-time seller. Auto deficiency + personal loans. Board needs RMAI language.",
    }),
    company({
      id: "co_sofi",
      name: "Summit Consumer Lending",
      domain: "summitlending.com",
      type: "seller",
      industry: "Fintech lender",
      city: "Salt Lake City",
      state: "UT",
      employees: "1,200",
      ownerId: "u_alex",
      lifecycle: "customer",
      score: 88,
      notes: "Fintech specialty paper. Strong media. Wants forward-flow term sheet.",
    }),
    company({
      id: "co_rmc",
      name: "Gulfshore Health System",
      domain: "gulfshorehealth.org",
      type: "seller",
      industry: "Healthcare",
      city: "Fort Myers",
      state: "FL",
      employees: "4,400",
      ownerId: "u_maya",
      lifecycle: "mql",
      score: 74,
      notes: "Medical receivables. HIPAA BAAs required before data room.",
    }),
    company({
      id: "co_onemain",
      name: "Harborpoint Consumer Finance",
      domain: "harborpointcf.com",
      type: "seller",
      industry: "Consumer finance",
      city: "Evansville",
      state: "IN",
      employees: "2,100",
      ownerId: "u_alex",
      lifecycle: "opportunity",
      score: 86,
      notes: "Personal loan charge-offs. Quarterly program since 2024.",
    }),
    company({
      id: "co_encore",
      name: "Northstar Receivables",
      domain: "northstarrecv.com",
      type: "buyer",
      industry: "Debt buyer",
      city: "San Diego",
      state: "CA",
      employees: "900",
      ownerId: "u_jordan",
      lifecycle: "customer",
      score: 95,
      notes: "Tier-1 buyer. Credit card + auto. Licensed in 48 states.",
    }),
    company({
      id: "co_pra",
      name: "Keystone Portfolio Partners",
      domain: "keystonepp.com",
      type: "buyer",
      industry: "Debt buyer",
      city: "Norfolk",
      state: "VA",
      employees: "1,400",
      ownerId: "u_jordan",
      lifecycle: "customer",
      score: 91,
      notes: "Aggressive on fresh primary. Wants media completeness ≥ 85%.",
    }),
    company({
      id: "co_cavalry",
      name: "Redwood Asset Recovery",
      domain: "redwoodar.com",
      type: "buyer",
      industry: "Debt buyer",
      city: "Phoenix",
      state: "AZ",
      employees: "320",
      ownerId: "u_jordan",
      lifecycle: "sql",
      score: 79,
      notes: "Medical and telecom specialist. Needs chain-of-title pack.",
    }),
    company({
      id: "co_unifund",
      name: "Meridian Credit Advisors",
      domain: "meridiancredit.com",
      type: "buyer",
      industry: "Collection / buyer",
      city: "Cincinnati",
      state: "OH",
      employees: "540",
      ownerId: "u_jordan",
      lifecycle: "opportunity",
      score: 83,
      notes: "Secondary and tertiary paper. Price-sensitive.",
    }),
    company({
      id: "co_counsel",
      name: "RMAI Counsel Network",
      domain: "rmaicounsel.com",
      type: "partner",
      industry: "Legal / compliance",
      city: "Washington",
      state: "DC",
      employees: "40",
      ownerId: "u_priya",
      lifecycle: "evangelist",
      score: 70,
      notes: "Outside counsel for purchase agreements and CFPB comment letters.",
    }),
  ];

  data.contacts = [
    contact({
      id: "ct_lena",
      firstName: "Lena",
      lastName: "Whitaker",
      email: "lena.whitaker@firsthorizon.com",
      phone: "(901) 555-0182",
      title: "SVP, Recoveries",
      companyId: "co_fhb",
      ownerId: "u_maya",
      lifecycle: "opportunity",
      score: 94,
      city: "Memphis",
      state: "TN",
      lastActivityAt: "2026-09-06T15:20:00.000Z",
      tags: ["seller", "credit-card", "repeat"],
    }),
    contact({
      id: "ct_omar",
      firstName: "Omar",
      lastName: "Delgado",
      email: "omar.delgado@atlanticcoastcu.org",
      phone: "(904) 555-0114",
      title: "VP, Collections",
      companyId: "co_navy",
      ownerId: "u_maya",
      lifecycle: "sql",
      score: 80,
      city: "Jacksonville",
      state: "FL",
      lastActivityAt: "2026-09-05T18:10:00.000Z",
      tags: ["seller", "auto", "first-sale"],
    }),
    contact({
      id: "ct_hana",
      firstName: "Hana",
      lastName: "Park",
      email: "hana.park@summitlending.com",
      phone: "(801) 555-0199",
      title: "Director, Credit Ops",
      companyId: "co_sofi",
      ownerId: "u_alex",
      lifecycle: "customer",
      score: 90,
      city: "Salt Lake City",
      state: "UT",
      lastActivityAt: "2026-09-07T13:40:00.000Z",
      tags: ["seller", "fintech", "forward-flow"],
    }),
    contact({
      id: "ct_ruth",
      firstName: "Ruth",
      lastName: "Caldwell",
      email: "rcaldwell@gulfshorehealth.org",
      phone: "(239) 555-0160",
      title: "Revenue Cycle Officer",
      companyId: "co_rmc",
      ownerId: "u_maya",
      lifecycle: "mql",
      score: 72,
      city: "Fort Myers",
      state: "FL",
      lastActivityAt: "2026-09-04T16:00:00.000Z",
      tags: ["seller", "medical", "hipaa"],
    }),
    contact({
      id: "ct_ben",
      firstName: "Ben",
      lastName: "Iverson",
      email: "biverson@harborpointcf.com",
      phone: "(812) 555-0133",
      title: "Head of Recoveries",
      companyId: "co_onemain",
      ownerId: "u_alex",
      lifecycle: "opportunity",
      score: 85,
      city: "Evansville",
      state: "IN",
      lastActivityAt: "2026-09-06T20:05:00.000Z",
      tags: ["seller", "personal-loans"],
    }),
    contact({
      id: "ct_sasha",
      firstName: "Sasha",
      lastName: "Moreau",
      email: "smoreau@northstarrecv.com",
      phone: "(619) 555-0177",
      title: "Chief Acquisitions Officer",
      companyId: "co_encore",
      ownerId: "u_jordan",
      lifecycle: "customer",
      score: 96,
      city: "San Diego",
      state: "CA",
      lastActivityAt: "2026-09-07T11:15:00.000Z",
      tags: ["buyer", "tier-1", "credit-card"],
    }),
    contact({
      id: "ct_eli",
      firstName: "Eli",
      lastName: "Nguyen",
      email: "eli.nguyen@keystonepp.com",
      phone: "(757) 555-0108",
      title: "VP, Portfolio Acquisitions",
      companyId: "co_pra",
      ownerId: "u_jordan",
      lifecycle: "customer",
      score: 89,
      city: "Norfolk",
      state: "VA",
      lastActivityAt: "2026-09-06T22:30:00.000Z",
      tags: ["buyer", "primary", "media-strict"],
    }),
    contact({
      id: "ct_amira",
      firstName: "Amira",
      lastName: "Hassan",
      email: "ahassan@redwoodar.com",
      phone: "(480) 555-0142",
      title: "Head of Diligence",
      companyId: "co_cavalry",
      ownerId: "u_jordan",
      lifecycle: "sql",
      score: 78,
      city: "Phoenix",
      state: "AZ",
      lastActivityAt: "2026-09-03T17:45:00.000Z",
      tags: ["buyer", "medical", "telecom"],
    }),
    contact({
      id: "ct_cole",
      firstName: "Cole",
      lastName: "Brennan",
      email: "cbrennan@meridiancredit.com",
      phone: "(513) 555-0129",
      title: "Acquisitions Manager",
      companyId: "co_unifund",
      ownerId: "u_jordan",
      lifecycle: "opportunity",
      score: 76,
      city: "Cincinnati",
      state: "OH",
      lastActivityAt: "2026-09-05T14:12:00.000Z",
      tags: ["buyer", "secondary"],
    }),
  ];

  data.inventory = [
    inventory({
      id: "inv_cc_fhb",
      name: "FHB CC Primary Q3-26",
      kind: "Credit card charge-off",
      sellerCompanyId: "co_fhb",
      faceValue: 48_200_000,
      askingPrice: 4_338_000,
      accountCount: 18640,
      avgBalance: 2586,
      vintage: "2025–2026",
      states: ["TN", "GA", "AL", "MS", "AR", "FL"],
      mediaQuality: "excellent",
      scoreBand: "540–680",
      status: "in_market",
      notes: "Fresh primary. Charge-off + last payment + statements. 14-day bid window.",
    }),
    inventory({
      id: "inv_auto_accu",
      name: "ACCU Auto Deficiency 2026-A",
      kind: "Auto deficiency",
      sellerCompanyId: "co_navy",
      faceValue: 12_750_000,
      askingPrice: 1_020_000,
      accountCount: 2144,
      avgBalance: 5947,
      vintage: "2023–2025",
      states: ["FL", "GA", "SC"],
      mediaQuality: "good",
      scoreBand: "500–640",
      status: "listed",
      notes: "Repo dates and auction net proceeds attached. Board packet pending.",
    }),
    inventory({
      id: "inv_pl_harbor",
      name: "Harborpoint PL Forward Flow Sep",
      kind: "Personal loans",
      sellerCompanyId: "co_onemain",
      faceValue: 22_400_000,
      askingPrice: 2_016_000,
      accountCount: 9102,
      avgBalance: 2461,
      vintage: "2026",
      states: ["IN", "OH", "KY", "IL", "MO"],
      mediaQuality: "excellent",
      scoreBand: "560–700",
      status: "in_market",
      notes: "Monthly forward flow. 90-day put-back for fraud and deceased.",
    }),
    inventory({
      id: "inv_med_gulf",
      name: "Gulfshore Self-Pay 2019-24",
      kind: "Medical receivables",
      sellerCompanyId: "co_rmc",
      faceValue: 31_800_000,
      askingPrice: 954_000,
      accountCount: 42110,
      avgBalance: 755,
      vintage: "2019–2024",
      states: ["FL"],
      mediaQuality: "fair",
      scoreBand: "unscored",
      status: "intake",
      notes: "BAA + itemized statements required. No emergency-room paper in this cut.",
    }),
    inventory({
      id: "inv_fin_summit",
      name: "Summit BNPL Charge-off 26B",
      kind: "Fintech specialty",
      sellerCompanyId: "co_sofi",
      faceValue: 9_650_000,
      askingPrice: 1_158_000,
      accountCount: 27880,
      avgBalance: 346,
      vintage: "2025–2026",
      states: ["CA", "TX", "NY", "FL", "IL"],
      mediaQuality: "excellent",
      scoreBand: "600–740",
      status: "awarded",
      notes: "Awarded to Northstar. Funding Friday. Digital media via SFTP.",
    }),
    inventory({
      id: "inv_tel_legacy",
      name: "Legacy Telecom Pack (brokered)",
      kind: "Telecom",
      sellerCompanyId: "co_sofi",
      faceValue: 6_200_000,
      askingPrice: 248_000,
      accountCount: 15400,
      avgBalance: 403,
      vintage: "2022–2024",
      states: ["TX", "OK", "LA"],
      mediaQuality: "poor",
      scoreBand: "480–580",
      status: "closed",
      notes: "Closed last month. Post-sale media reconciliation open.",
    }),
  ];

  data.deals = [
    deal({
      id: "de_fhb_q3",
      name: "FHB CC Primary Q3-26 — bid window",
      companyId: "co_fhb",
      contactId: "ct_lena",
      inventoryId: "inv_cc_fhb",
      ownerId: "u_maya",
      stage: "Bid window",
      amount: 4_338_000,
      closeDate: "2026-09-22",
      probability: 62,
      forecast: "best_case",
      nextStep: "Collect second-round bids from Northstar and Keystone by Thursday 4pm ET.",
    }),
    deal({
      id: "de_accu_auto",
      name: "ACCU Auto Deficiency — NDA / board",
      companyId: "co_navy",
      contactId: "ct_omar",
      inventoryId: "inv_auto_accu",
      ownerId: "u_maya",
      stage: "NDA executed",
      amount: 1_020_000,
      closeDate: "2026-10-10",
      probability: 40,
      forecast: "pipeline",
      nextStep: "Send RMAI-aligned board memo and sample sale agreement.",
    }),
    deal({
      id: "de_harbor_ff",
      name: "Harborpoint PL forward flow",
      companyId: "co_onemain",
      contactId: "ct_ben",
      inventoryId: "inv_pl_harbor",
      ownerId: "u_alex",
      stage: "Data room live",
      amount: 2_016_000,
      closeDate: "2026-09-30",
      probability: 55,
      forecast: "commit",
      nextStep: "Walk Keystone through tape layout and put-back mechanics.",
    }),
    deal({
      id: "de_gulf_med",
      name: "Gulfshore medical self-pay",
      companyId: "co_rmc",
      contactId: "ct_ruth",
      inventoryId: "inv_med_gulf",
      ownerId: "u_maya",
      stage: "Seller intake",
      amount: 954_000,
      closeDate: "2026-10-28",
      probability: 25,
      forecast: "pipeline",
      nextStep: "Execute BAA and confirm no ER paper in extract.",
    }),
    deal({
      id: "de_summit_award",
      name: "Summit BNPL awarded — fund",
      companyId: "co_sofi",
      contactId: "ct_hana",
      inventoryId: "inv_fin_summit",
      ownerId: "u_alex",
      stage: "Funding & close",
      amount: 1_158_000,
      closeDate: "2026-09-12",
      probability: 90,
      forecast: "commit",
      nextStep: "Wire instructions + SFTP credentials to Northstar.",
    }),
    deal({
      id: "de_redwood_tel",
      name: "Redwood telecom add-on",
      companyId: "co_cavalry",
      contactId: "ct_amira",
      inventoryId: "inv_tel_legacy",
      ownerId: "u_jordan",
      stage: "Post-sale media",
      amount: 248_000,
      closeDate: "2026-08-18",
      probability: 100,
      forecast: "closed",
      nextStep: "Reconcile 412 missing statements.",
    }),
  ];

  data.activities = [
    activity({
      id: "ac_1",
      type: "email",
      subject: "Bid window open — FHB CC Primary Q3-26",
      body: "Lena, the data room is live for Northstar and Keystone. Bid deadline Thursday 4pm ET. We will run a sealed second round if spreads are inside 40 bps.",
      at: "2026-09-06T15:20:00.000Z",
      userId: "u_maya",
      contactId: "ct_lena",
      companyId: "co_fhb",
      dealId: "de_fhb_q3",
    }),
    activity({
      id: "ac_2",
      type: "call",
      subject: "Board education call with ACCU",
      body: "Omar wants a one-pager that distinguishes brokerage from collection. Confirmed Triton does not contact consumers. Follow up with RMAI language.",
      at: "2026-09-05T18:10:00.000Z",
      userId: "u_maya",
      contactId: "ct_omar",
      companyId: "co_navy",
      dealId: "de_accu_auto",
    }),
    activity({
      id: "ac_3",
      type: "meeting",
      subject: "Award recap — Summit BNPL",
      body: "Hana and Sasha aligned on Friday funding. Media via SFTP. 90-day fraud put-back remains.",
      at: "2026-09-07T13:40:00.000Z",
      userId: "u_alex",
      contactId: "ct_hana",
      companyId: "co_sofi",
      dealId: "de_summit_award",
    }),
    activity({
      id: "ac_4",
      type: "note",
      subject: "Keystone media threshold",
      body: "Eli will not bid primary below 85% statement completeness. FHB tape is 93% — good to go.",
      at: "2026-09-06T22:30:00.000Z",
      userId: "u_jordan",
      contactId: "ct_eli",
      companyId: "co_pra",
      dealId: "de_fhb_q3",
    }),
    activity({
      id: "ac_5",
      type: "ai",
      subject: "Breeze scored FHB Q3 tape",
      body: "AI estimate: 8.6–9.4¢ fair range given vintage, media, and Southeast concentration. Asking 9.0¢ is supportable if two tier-1 buyers stay in.",
      at: "2026-09-07T09:05:00.000Z",
      userId: "u_alex",
      companyId: "co_fhb",
      dealId: "de_fhb_q3",
    }),
  ];

  data.tasks = [
    task({
      id: "tk_1",
      title: "Collect second-round bids — FHB Q3",
      due: "2026-09-11",
      status: "open",
      priority: "high",
      ownerId: "u_maya",
      contactId: "ct_lena",
      dealId: "de_fhb_q3",
    }),
    task({
      id: "tk_2",
      title: "Draft ACCU board memo (RMAI / FDCPA)",
      due: "2026-09-09",
      status: "open",
      priority: "urgent",
      ownerId: "u_priya",
      contactId: "ct_omar",
      dealId: "de_accu_auto",
    }),
    task({
      id: "tk_3",
      title: "Issue Summit wire instructions",
      due: "2026-09-10",
      status: "open",
      priority: "high",
      ownerId: "u_alex",
      contactId: "ct_hana",
      dealId: "de_summit_award",
    }),
    task({
      id: "tk_4",
      title: "Reconcile Redwood missing statements",
      due: "2026-09-12",
      status: "open",
      priority: "medium",
      ownerId: "u_jordan",
      contactId: "ct_amira",
      dealId: "de_redwood_tel",
    }),
    task({
      id: "tk_5",
      title: "Execute Gulfshore BAA",
      due: "2026-09-15",
      status: "open",
      priority: "medium",
      ownerId: "u_priya",
      contactId: "ct_ruth",
      dealId: "de_gulf_med",
    }),
  ];

  data.tickets = [
    ticket({
      id: "ti_1",
      subject: "Data room access — Keystone on FHB Q3",
      status: "in_progress",
      priority: "high",
      requesterId: "ct_eli",
      companyId: "co_pra",
      ownerId: "u_jordan",
      pipeline: "Buyer operations",
      createdAt: "2026-09-06T12:00:00.000Z",
      preview: "Eli needs watermarked CSV + sale agreement draft before they can bid.",
    }),
    ticket({
      id: "ti_2",
      subject: "HIPAA BAA template for Gulfshore",
      status: "waiting",
      priority: "high",
      requesterId: "ct_ruth",
      companyId: "co_rmc",
      ownerId: "u_priya",
      pipeline: "Compliance",
      createdAt: "2026-09-04T16:20:00.000Z",
      preview: "Hospital counsel asked for Triton's standard BAA plus no-consumer-contact attestation.",
    }),
    ticket({
      id: "ti_3",
      subject: "Post-sale media gap — 412 statements",
      status: "new",
      priority: "medium",
      requesterId: "ct_amira",
      companyId: "co_cavalry",
      ownerId: "u_jordan",
      pipeline: "Post-sale",
      createdAt: "2026-09-07T10:02:00.000Z",
      preview: "Redwood flagged missing statements on the closed telecom pack.",
    }),
    ticket({
      id: "ti_4",
      subject: "Buyer license pack refresh — Northstar NY",
      status: "resolved",
      priority: "low",
      requesterId: "ct_sasha",
      companyId: "co_encore",
      ownerId: "u_priya",
      pipeline: "Compliance",
      createdAt: "2026-08-28T14:00:00.000Z",
      preview: "NY license uploaded. Cleared for FHB bid.",
    }),
  ];

  data.conversations = [
    conversation({
      id: "cv_1",
      channel: "email",
      subject: "Re: FHB Q3 bid instructions",
      contactId: "ct_sasha",
      companyId: "co_encore",
      lastAt: "2026-09-07T11:15:00.000Z",
      unread: true,
      messages: [
        {
          id: "m1",
          from: "us",
          body: "Sasha — data room is open. Sealed bids due Thursday 4pm ET. Asking 9.0¢ on $48.2M face.",
          at: "2026-09-06T15:40:00.000Z",
        },
        {
          id: "m2",
          from: "them",
          body: "We'll be in. Confirming 90-day fraud / deceased put-back and no settlement accounts in the cut?",
          at: "2026-09-07T11:15:00.000Z",
        },
      ],
    }),
    conversation({
      id: "cv_2",
      channel: "email",
      subject: "Board packet — selling auto deficiency",
      contactId: "ct_omar",
      companyId: "co_navy",
      lastAt: "2026-09-05T18:40:00.000Z",
      unread: false,
      messages: [
        {
          id: "m3",
          from: "them",
          body: "Can you send language our board can use that we are not hiring a collection agency?",
          at: "2026-09-05T18:12:00.000Z",
        },
        {
          id: "m4",
          from: "us",
          body: "Yes — Triton is a buyer/broker of charged-off receivables. We do not contact consumers. Draft memo coming today.",
          at: "2026-09-05T18:40:00.000Z",
        },
      ],
    }),
    conversation({
      id: "cv_3",
      channel: "portal",
      subject: "Funding checklist — Summit BNPL",
      contactId: "ct_hana",
      companyId: "co_sofi",
      lastAt: "2026-09-07T13:55:00.000Z",
      unread: false,
      messages: [
        {
          id: "m5",
          from: "them",
          body: "Wire desk is ready. Need final allocation schedule and SFTP path.",
          at: "2026-09-07T13:55:00.000Z",
        },
      ],
    }),
  ];

  data.campaigns = [
    campaign({
      id: "ca_1",
      name: "Seller: 2026 Charge-off Liquidity Series",
      type: "email",
      status: "running",
      audience: "Bank & CU recoveries leaders",
      sent: 1840,
      opened: 612,
      clicked: 147,
      replies: 38,
      ownerId: "u_noah",
    }),
    campaign({
      id: "ca_2",
      name: "Buyer: Fresh primary alerts",
      type: "email",
      status: "running",
      audience: "Qualified buyers — credit card / auto",
      sent: 226,
      opened: 171,
      clicked: 88,
      replies: 24,
      ownerId: "u_jordan",
    }),
    campaign({
      id: "ca_3",
      name: "RMAI conference follow-up",
      type: "sequence",
      status: "completed",
      audience: "Booth scans — Las Vegas",
      sent: 94,
      opened: 61,
      clicked: 22,
      replies: 11,
      ownerId: "u_maya",
    }),
    campaign({
      id: "ca_4",
      name: "LinkedIn — DebtMarket Hub",
      type: "ads",
      status: "scheduled",
      audience: "Recoveries + acquisitions titles",
      sent: 0,
      opened: 0,
      clicked: 0,
      replies: 0,
      ownerId: "u_noah",
    }),
  ];

  data.emails = [
    email({
      id: "em_1",
      name: "How banks monetize Q4 charge-offs",
      subject: "A cleaner 14–45 day path to liquidity",
      status: "running",
      campaignId: "ca_1",
      preview:
        "Triton Financial Solutions operates DebtMarket — an institutional marketplace, not a collection agency.",
    }),
    email({
      id: "em_2",
      name: "New listing: FHB CC Primary",
      subject: "Fresh primary in the Southeast — bids Thursday",
      status: "completed",
      campaignId: "ca_2",
      preview: "Face $48.2M · asking 9.0¢ · excellent media · sealed bid.",
    }),
    email({
      id: "em_3",
      name: "Medical sellers: BAA-first process",
      subject: "Sell self-pay paper without leaking PHI",
      status: "draft",
      campaignId: "ca_1",
      preview: "HIPAA BAA before any tape. No consumer contact. Documentation discipline.",
    }),
  ];

  data.segments = [
    segment({
      id: "sg_1",
      name: "Tier-1 credit-card buyers",
      count: 18,
      definition: "Buyer · licensed 40+ states · credit-card · score ≥ 85",
    }),
    segment({
      id: "sg_2",
      name: "First-time credit union sellers",
      count: 41,
      definition: "Seller · credit union · no closed deal · lifecycle ≥ MQL",
    }),
    segment({
      id: "sg_3",
      name: "Medical / HIPAA track",
      count: 12,
      definition: "Industry contains Healthcare OR tag medical",
    }),
  ];

  data.forms = [
    form({
      id: "fo_1",
      name: "Sell a portfolio — intake",
      submissions: 64,
      conversion: 18,
      page: "/sell",
    }),
    form({
      id: "fo_2",
      name: "Buyer qualification",
      submissions: 29,
      conversion: 41,
      page: "/buyers",
    }),
    form({
      id: "fo_3",
      name: "NDA request",
      submissions: 22,
      conversion: 73,
      page: "/data-room",
    }),
  ];

  data.sequences = [
    sequence({
      id: "sq_1",
      name: "Seller recovery — 5 touches",
      steps: 5,
      enrolled: 38,
      replied: 11,
      meetings: 6,
    }),
    sequence({
      id: "sq_2",
      name: "Buyer onboarding — license pack",
      steps: 4,
      enrolled: 14,
      replied: 9,
      meetings: 4,
    }),
  ];

  data.pages = [
    page({
      id: "pg_1",
      title: "DebtMarket — Institutional receivables marketplace",
      slug: "/",
      type: "website",
      status: "published",
      views: 18420,
      updatedAt: "2026-09-01",
      excerpt: "Buy and sell charged-off portfolios. 14–45 day closes. FDCPA-aware. RMAI-aligned.",
    }),
    page({
      id: "pg_2",
      title: "About Triton Financial Solutions",
      slug: "/about-us-triton-financial-solutions",
      type: "website",
      status: "published",
      views: 4210,
      updatedAt: "2026-08-20",
      excerpt: "Licensed debt buyer, broker, and marketplace. Coconut Creek, FL.",
    }),
    page({
      id: "pg_3",
      title: "Sell a charged-off portfolio",
      slug: "/sell",
      type: "landing",
      status: "published",
      views: 2880,
      updatedAt: "2026-09-04",
      excerpt: "Intake for banks, credit unions, fintechs, and health systems.",
    }),
    page({
      id: "pg_4",
      title: "Qualified buyer network",
      slug: "/buyers",
      type: "landing",
      status: "published",
      views: 1960,
      updatedAt: "2026-09-03",
      excerpt: "200+ compliance-verified buyers. License pack required.",
    }),
    page({
      id: "pg_5",
      title: "What “cents on the dollar” actually means",
      slug: "/blog/cents-on-the-dollar",
      type: "blog",
      status: "published",
      views: 7340,
      updatedAt: "2026-08-12",
      excerpt: "How face, media, vintage, and state mix move bid ranges.",
    }),
    page({
      id: "pg_6",
      title: "CU board memo: selling deficiency balances",
      slug: "/blog/credit-union-board-memo",
      type: "blog",
      status: "review",
      views: 0,
      updatedAt: "2026-09-07",
      excerpt: "Draft for ACCU and similar first-time sellers.",
    }),
  ];

  data.keywords = [
    keyword({
      id: "kw_1",
      term: "sell charged off debt portfolio",
      volume: 720,
      position: 4,
      difficulty: 38,
      url: "/sell",
      intent: "transactional",
    }),
    keyword({
      id: "kw_2",
      term: "buy charged off credit card debt",
      volume: 880,
      position: 6,
      difficulty: 44,
      url: "/buyers",
      intent: "transactional",
    }),
    keyword({
      id: "kw_3",
      term: "debt buyer marketplace",
      volume: 390,
      position: 3,
      difficulty: 29,
      url: "/",
      intent: "commercial",
    }),
    keyword({
      id: "kw_4",
      term: "what is cents on the dollar debt",
      volume: 1400,
      position: 8,
      difficulty: 22,
      url: "/blog/cents-on-the-dollar",
      intent: "informational",
    }),
    keyword({
      id: "kw_5",
      term: "sell medical receivables charged off",
      volume: 210,
      position: 11,
      difficulty: 33,
      url: "/sell",
      intent: "commercial",
    }),
    keyword({
      id: "kw_6",
      term: "Triton Financial Solutions",
      volume: 160,
      position: 1,
      difficulty: 12,
      url: "/about-us-triton-financial-solutions",
      intent: "navigational",
    }),
  ];

  data.audits = [
    audit({
      id: "au_1",
      severity: "high",
      title: "Seller landing missing FAQ schema",
      page: "/sell",
      recommendation: "Add FAQPage JSON-LD for institutional-only + no consumer contact.",
    }),
    audit({
      id: "au_2",
      severity: "medium",
      title: "Thin internal links from blog to buyer form",
      page: "/blog/cents-on-the-dollar",
      recommendation: "Add contextual CTA to /buyers after the bid-range table.",
    }),
    audit({
      id: "au_3",
      severity: "low",
      title: "OG image not set on medical draft",
      page: "/blog/credit-union-board-memo",
      recommendation: "Generate 1200×630 before publish.",
    }),
  ];

  data.workflows = [
    workflow({
      id: "wf_1",
      name: "Seller form → CRM + NDA task",
      status: "active",
      trigger: "Form submitted: Sell a portfolio",
      enrolled: 64,
      goal: "Create company + contact, assign Maya, create NDA task",
    }),
    workflow({
      id: "wf_2",
      name: "Buyer bid reminder — T-24h",
      status: "active",
      trigger: "Deal stage = Bid window AND closeDate − 1 day",
      enrolled: 9,
      goal: "Email owner + inbox the buyer list",
    }),
    workflow({
      id: "wf_3",
      name: "License expired → pause bids",
      status: "active",
      trigger: "Buyer license expiring in 14 days",
      enrolled: 3,
      goal: "Ticket to Compliance, remove from bid list",
    }),
    workflow({
      id: "wf_4",
      name: "Post-sale media SLA",
      status: "paused",
      trigger: "Deal stage = Post-sale media",
      enrolled: 2,
      goal: "Daily reminder until media ticket resolved",
    }),
  ];

  data.reports = [
    report({
      id: "rp_1",
      name: "Brokerage forecast — Sep",
      hub: "sales",
      insight: "$7.51M weighted pipeline. $1.16M commit this week (Summit).",
    }),
    report({
      id: "rp_2",
      name: "Seller campaign funnel",
      hub: "marketing",
      insight: "33% open on liquidity series. 38 replies → 6 meetings.",
    }),
    report({
      id: "rp_3",
      name: "Buyer coverage by asset class",
      hub: "marketplace",
      insight: "Credit card over-covered. Medical buyers thin — recruit 3.",
    }),
  ];

  data.quotes = [
    quote({
      id: "qt_1",
      dealId: "de_fhb_q3",
      name: "Indicative 9.0¢ — FHB Q3",
      amount: 4_338_000,
      status: "sent",
    }),
    quote({
      id: "qt_2",
      dealId: "de_summit_award",
      name: "Award — Summit BNPL 12.0¢",
      amount: 1_158_000,
      status: "accepted",
    }),
  ];

  data.meetings = [
    meeting({
      id: "mt_1",
      title: "FHB bid recap",
      when: "2026-09-11T20:00:00.000Z",
      contactId: "ct_lena",
      dealId: "de_fhb_q3",
      location: "Zoom · Triton desk",
    }),
    meeting({
      id: "mt_2",
      title: "ACCU board education",
      when: "2026-09-10T16:00:00.000Z",
      contactId: "ct_omar",
      dealId: "de_accu_auto",
      location: "Teams",
    }),
  ];

  data.aiMessages = [
    {
      id: "ai_0",
      role: "assistant",
      body: "I'm Meridian AI for Triton / DebtMarket. I can score portfolios, draft buyer/seller emails, summarize bid windows, and keep FDCPA / no-consumer-contact language clean. Ask about FHB Q3 or ACCU.",
      at: "2026-09-07T08:00:00.000Z",
    },
  ];

  return data;
}
