import type { Account, Agent, AppData, Payment, PaymentPlan, ScriptVersion, TimelineEvent } from "./types";

function agent(
  id: string,
  name: string,
  role: string,
  initials: string,
  status: Agent["status"],
  callsToday: number,
  collectedToday: number,
  clockedInAt?: string,
): Agent {
  return { id, name, role, initials, status, callsToday, collectedToday, clockedInAt };
}

function acc(partial: Account): Account {
  return partial;
}

export function seedCove(): AppData {
  const agents: Agent[] = [
    agent("ag_devon", "Devon Blake", "Collector", "DB", "offline", 0, 0),
    agent("ag_sam", "Sam Ruiz", "Collector", "SR", "available", 18, 640, "2026-09-07T13:02:00.000Z"),
    agent("ag_casey", "Casey Quinn", "Collector", "CQ", "on_call", 22, 910, "2026-09-07T12:48:00.000Z"),
    agent("ag_jordan", "Jordan Hale", "Floor lead", "JH", "available", 9, 420, "2026-09-07T12:10:00.000Z"),
    agent("ag_priya", "Priya Shah", "Compliance", "PS", "break", 0, 0, "2026-09-07T13:30:00.000Z"),
  ];

  const accounts: Account[] = [
    acc({
      id: "ac_ga_1",
      firstName: "Marisol",
      lastName: "Bennett",
      phone: "(404) 555-0142",
      email: "m.bennett.demo@example.com",
      address: "184 Piedmont Ave",
      city: "Atlanta",
      state: "GA",
      zip: "30308",
      timezone: "America/New_York",
      last4: "4412",
      originalCreditor: "Harborpoint Consumer Finance",
      portfolio: "Harborpoint PL Forward Flow Sep",
      product: "Personal loan",
      chargeOff: "2026-03-12",
      placedAt: "2026-08-20",
      balance: 2840,
      original: 3100,
      status: "working",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 72,
      social: [
        { network: "facebook", handle: "public profile match · Atlanta", confidence: 68, note: "City + last name only. Do not friend." },
        { network: "linkedin", handle: "Not found", confidence: 12, note: "No confident professional match." },
      ],
      skipHits: [
        { id: "sk1", kind: "phone", value: "(404) 555-0177", confidence: 71, source: "Lexis-class header" },
        { id: "sk2", kind: "employer", value: "Dekalb logistics (possible)", confidence: 44, source: "credit header" },
      ],
      notes: "Asked about a $75 biweekly. Wants Friday payday.",
    }),
    acc({
      id: "ac_ky_1",
      firstName: "Ellis",
      lastName: "Crowder",
      phone: "(502) 555-0119",
      email: "ellis.crowder.demo@example.com",
      address: "90 Story Ave",
      city: "Louisville",
      state: "KY",
      zip: "40206",
      timezone: "America/New_York",
      last4: "9031",
      originalCreditor: "Atlantic Coast Credit Union",
      portfolio: "ACCU Auto Deficiency 2026-A",
      product: "Auto deficiency",
      chargeOff: "2025-11-02",
      placedAt: "2026-08-28",
      balance: 6120,
      original: 6400,
      status: "validation_sent",
      language: "en",
      consent: { voice: true, sms: false, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: false,
      score: 54,
      social: [{ network: "nextdoor", handle: "No match", confidence: 8, note: "Skip only — no social outreach." }],
      skipHits: [],
      notes: "Left VM. No SMS consent.",
    }),
    acc({
      id: "ac_sc_1",
      firstName: "Tasha",
      lastName: "Ingram",
      phone: "(843) 555-0164",
      email: "tasha.ingram.demo@example.com",
      address: "22 King St",
      city: "Charleston",
      state: "SC",
      zip: "29401",
      timezone: "America/New_York",
      last4: "2288",
      originalCreditor: "Summit Consumer Lending",
      portfolio: "Summit BNPL Charge-off 26B",
      product: "BNPL",
      chargeOff: "2026-01-18",
      placedAt: "2026-09-01",
      balance: 418,
      original: 460,
      status: "ptp",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 81,
      social: [],
      skipHits: [],
      notes: "PTP $100 on the 12th. Card on file ending 4419.",
    }),
    acc({
      id: "ac_mo_1",
      firstName: "Hank",
      lastName: "Voss",
      phone: "(314) 555-0183",
      email: "hank.voss.demo@example.com",
      address: "4100 Gravois",
      city: "St. Louis",
      state: "MO",
      zip: "63116",
      timezone: "America/Chicago",
      last4: "7720",
      originalCreditor: "First Horizon Bank",
      portfolio: "FHB CC Primary Q3-26",
      product: "Credit card",
      chargeOff: "2026-04-09",
      placedAt: "2026-09-03",
      balance: 1940,
      original: 2100,
      status: "new",
      language: "en",
      consent: { voice: true, sms: true, email: false, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: false,
      miniMiranda: false,
      score: 61,
      social: [],
      skipHits: [],
      notes: "Validation not yet mailed. Bot should send before first demand.",
    }),
    acc({
      id: "ac_ms_1",
      firstName: "Keisha",
      lastName: "Alston",
      phone: "(601) 555-0106",
      email: "keisha.alston.demo@example.com",
      address: "7 Farish St",
      city: "Jackson",
      state: "MS",
      zip: "39201",
      timezone: "America/Chicago",
      last4: "1194",
      originalCreditor: "Gulfshore Health System",
      portfolio: "Gulfshore Self-Pay (consumer placed)",
      product: "Medical self-pay",
      chargeOff: "2024-09-01",
      placedAt: "2026-08-15",
      balance: 880,
      original: 1200,
      status: "dispute",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 40,
      social: [],
      skipHits: [],
      notes: "Verbal dispute 9/4. Hold collections. Itemization requested.",
    }),
    acc({
      id: "ac_oh_1",
      firstName: "Noah",
      lastName: "Pellegrino",
      phone: "(216) 555-0135",
      email: "noah.p.demo@example.com",
      address: "1200 W 6th",
      city: "Cleveland",
      state: "OH",
      zip: "44113",
      timezone: "America/New_York",
      last4: "5502",
      originalCreditor: "Harborpoint Consumer Finance",
      portfolio: "Harborpoint PL Forward Flow Sep",
      product: "Personal loan",
      chargeOff: "2025-12-20",
      placedAt: "2026-08-22",
      balance: 3560,
      original: 3900,
      status: "working",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      nextCallAfter: "2026-09-08T15:00:00.000Z",
      score: 66,
      social: [
        { network: "linkedin", handle: "possible warehouse supervisor · Cuyahoga", confidence: 39, note: "Low confidence. Do not message." },
      ],
      skipHits: [{ id: "sk3", kind: "phone", value: "(440) 555-0190", confidence: 63, source: "utilities header" }],
      notes: "Third no-contact. Skip recommended.",
    }),
    acc({
      id: "ac_ca_block",
      firstName: "Riley",
      lastName: "Nguyen",
      phone: "(415) 555-0120",
      email: "riley.nguyen.demo@example.com",
      address: "88 Mission",
      city: "San Francisco",
      state: "CA",
      zip: "94105",
      timezone: "America/Los_Angeles",
      last4: "8801",
      originalCreditor: "Summit Consumer Lending",
      portfolio: "Held — licensed state",
      product: "Personal loan",
      chargeOff: "2026-02-01",
      placedAt: "2026-09-01",
      balance: 2400,
      original: 2400,
      status: "hold",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: false,
      miniMiranda: false,
      score: 50,
      social: [],
      skipHits: [],
      notes: "California — DFPI license required. Dialer will refuse.",
    }),
    acc({
      id: "ac_ok_1",
      firstName: "Jade",
      lastName: "Harjo",
      phone: "(405) 555-0171",
      email: "jade.harjo.demo@example.com",
      address: "15 Western Ave",
      city: "Oklahoma City",
      state: "OK",
      zip: "73102",
      timezone: "America/Chicago",
      last4: "3340",
      originalCreditor: "Atlantic Coast Credit Union",
      portfolio: "ACCU Auto Deficiency 2026-A",
      product: "Auto deficiency",
      chargeOff: "2026-05-14",
      placedAt: "2026-09-02",
      balance: 4780,
      original: 5100,
      status: "plan",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 77,
      social: [],
      skipHits: [],
      notes: "Active $200 monthly ACH plan.",
    }),
  ];

  const plans: PaymentPlan[] = [
    {
      id: "pl_1",
      accountId: "ac_ok_1",
      installment: 200,
      remaining: 5,
      cadence: "monthly",
      nextDue: "2026-10-02",
      method: "ach",
      status: "active",
    },
    {
      id: "pl_2",
      accountId: "ac_sc_1",
      installment: 100,
      remaining: 4,
      cadence: "monthly",
      nextDue: "2026-09-12",
      method: "card",
      status: "active",
    },
  ];

  const payments: Payment[] = [
    {
      id: "py_1",
      accountId: "ac_ok_1",
      amount: 200,
      method: "ach",
      at: "2026-09-02T16:10:00.000Z",
      last4: "1182",
      status: "approved",
    },
    {
      id: "py_2",
      accountId: "ac_ga_1",
      amount: 75,
      method: "card",
      at: "2026-09-05T18:22:00.000Z",
      last4: "4419",
      status: "approved",
    },
  ];

  const timeline: TimelineEvent[] = [
    {
      id: "tl_1",
      accountId: "ac_ga_1",
      channel: "call",
      title: "Right-party contact · 4m 12s",
      body: "Mini-Miranda delivered. Consumer asked for $75 biweekly starting Friday payday. Offered portal link.",
      at: "2026-09-05T18:10:00.000Z",
      actor: "Sam Ruiz",
      outcome: "RPC · soft PTP",
    },
    {
      id: "tl_2",
      accountId: "ac_ga_1",
      channel: "payment",
      title: "Card payment $75",
      body: "Visa •4419 authorized. Balance 2,840.",
      at: "2026-09-05T18:22:00.000Z",
      actor: "Cove Pay",
      outcome: "approved",
    },
    {
      id: "tl_3",
      accountId: "ac_ga_1",
      channel: "sms",
      title: "Authenticated SMS (10DLC)",
      body: "This is a debt collector. Confirmation: $75 received. Reply STOP to opt out.",
      at: "2026-09-05T18:24:00.000Z",
      actor: "SMS agent",
      outcome: "delivered",
    },
    {
      id: "tl_4",
      accountId: "ac_mo_1",
      channel: "system",
      title: "Account placed",
      body: "FHB CC primary. Missouri — no state license. Validation not sent.",
      at: "2026-09-03T14:00:00.000Z",
      actor: "Cove",
    },
    {
      id: "tl_5",
      accountId: "ac_ms_1",
      channel: "call",
      title: "Verbal dispute",
      body: "Consumer disputes amount and asked for itemization. Collections paused.",
      at: "2026-09-04T16:40:00.000Z",
      actor: "Casey Quinn",
      outcome: "dispute",
    },
    {
      id: "tl_6",
      accountId: "ac_oh_1",
      channel: "call",
      title: "No contact · 3rd attempt",
      body: "Ring-no-answer. Cool-down set. Skip recommended.",
      at: "2026-09-06T19:05:00.000Z",
      actor: "Voice agent v3",
      outcome: "no_contact",
    },
    {
      id: "tl_7",
      accountId: "ac_sc_1",
      channel: "email",
      title: "Authenticated email (DMARC pass)",
      body: "PTP reminder for $100 on Sep 12. Mini-Miranda in footer.",
      at: "2026-09-06T12:00:00.000Z",
      actor: "Email agent",
      outcome: "opened",
    },
    {
      id: "tl_8",
      accountId: "ac_ca_block",
      channel: "system",
      title: "Hold — licensed state",
      body: "California DFPI license required. Outbound channels locked.",
      at: "2026-09-01T15:00:00.000Z",
      actor: "State gate",
    },
  ];

  const scripts: ScriptVersion[] = [
    {
      id: "sc_1",
      version: 1,
      body: "Hello, may I speak with {{name}}? This is {{agent}} calling from Cove Recovery on a recorded line. This is an attempt to collect a debt…",
      createdAt: "2026-08-01",
      reason: "Initial compliance script",
      rpcRate: 0.18,
      ptpRate: 0.07,
      complaintRate: 0.012,
      naturalness: 0.54,
    },
    {
      id: "sc_2",
      version: 2,
      body: "Hi — looking for {{name}}. I’m {{agent}} with Cove Recovery. I’ll keep this short. This is an attempt to collect a debt, and anything you share is used for that. I have the Harborpoint personal loan ending {{last4}}…",
      createdAt: "2026-08-20",
      reason: "Less stacked disclosures up front; same mini-Miranda, more breath.",
      rpcRate: 0.23,
      ptpRate: 0.11,
      complaintRate: 0.009,
      naturalness: 0.71,
    },
    {
      id: "sc_3",
      version: 3,
      body: "Hey {{name}}? {{agent}} at Cove Recovery, recorded line. I’m a debt collector — this is an attempt to collect a debt. I can take card or ACH, or a Friday payday plan if that’s easier. What’s a number that works this week?",
      createdAt: "2026-09-04",
      reason: "Self-improve: v2 dropped after “I have the account” too fast. Offer a path before reciting balance.",
      rpcRate: 0.27,
      ptpRate: 0.14,
      complaintRate: 0.008,
      naturalness: 0.8,
    },
  ];

  return {
    agents,
    accounts,
    plans,
    payments,
    timeline,
    scripts,
    queue: [],
    messages: [],
    liveCall: null,
    currentAgentId: null,
    autoBot: false,
  };
}
