import { TEMPLATES } from "./templates";
import type {
  AccessGrant,
  Account,
  Agent,
  AppData,
  CallReview,
  Payment,
  PaymentPlan,
  Portfolio,
  ScriptVersion,
  TimelineEvent,
} from "./types";

interface AgentSeed {
  id: string;
  name: string;
  role: string;
  initials: string;
  status: Agent["status"];
  callsToday: number;
  collectedToday: number;
  clockedInAt?: string;
  employment: Agent["employment"];
  remote: boolean;
  location: string;
  maxAccounts: number;
  hourlyCost: number;
  commissionPct: number;
  qaScore: number;
  startedAt: string;
}

function agent(seed: AgentSeed): Agent {
  return seed;
}

/** Fields every seeded account shares unless it overrides them. */
type AccountSeed = Omit<Account, "phones" | "documents" | "portalCode"> &
  Partial<Pick<Account, "phones" | "documents" | "portalCode">>;

let codeCounter = 100;

function acc(partial: AccountSeed): Account {
  codeCounter += 7;
  return {
    ...partial,
    portalCode: partial.portalCode ?? `TFR-${partial.state}${codeCounter}-${partial.last4}`,
    phones:
      partial.phones ??
      [
        {
          id: `${partial.id}_ph1`,
          number: partial.phone,
          label: "primary" as const,
          status: "good" as const,
          attempts: 0,
        },
        ...partial.skipHits
          .filter((hit) => hit.kind === "phone")
          .map((hit) => ({
            id: `${partial.id}_${hit.id}`,
            number: hit.value,
            label: "skip" as const,
            status: "unverified" as const,
            attempts: 0,
          })),
      ],
    documents:
      partial.documents ??
      [
        {
          id: `${partial.id}_doc1`,
          accountId: partial.id,
          kind: "placement_file" as const,
          name: "Placement record (seller tape row)",
          addedAt: partial.placedAt,
          source: "Seller data file",
          verified: true,
          sizeKb: 6,
        },
        ...(partial.validationSent
          ? [
              {
                id: `${partial.id}_doc2`,
                accountId: partial.id,
                kind: "validation_letter" as const,
                name: "Reg F validation notice (mailed)",
                addedAt: partial.placedAt,
                source: "Print-and-mail API",
                verified: true,
                sizeKb: 88,
              },
            ]
          : []),
      ],
  };
}

export function seedCove(): AppData {
  const agents: Agent[] = [
    agent({
      id: "ag_devon",
      name: "Devon Blake",
      role: "Collector",
      initials: "DB",
      status: "offline",
      callsToday: 0,
      collectedToday: 0,
      employment: "1099",
      remote: true,
      location: "Tampa, FL",
      maxAccounts: 40,
      hourlyCost: 0,
      commissionPct: 18,
      qaScore: 88,
      startedAt: "2026-08-18",
    }),
    agent({
      id: "ag_sam",
      name: "Sam Ruiz",
      role: "Collector",
      initials: "SR",
      status: "available",
      callsToday: 18,
      collectedToday: 640,
      clockedInAt: "2026-09-07T13:02:00.000Z",
      employment: "1099",
      remote: true,
      location: "Phoenix, AZ",
      maxAccounts: 60,
      hourlyCost: 0,
      commissionPct: 20,
      qaScore: 94,
      startedAt: "2026-07-02",
    }),
    agent({
      id: "ag_casey",
      name: "Casey Quinn",
      role: "Collector",
      initials: "CQ",
      status: "on_call",
      callsToday: 22,
      collectedToday: 910,
      clockedInAt: "2026-09-07T12:48:00.000Z",
      employment: "w2",
      remote: false,
      location: "Atlanta, GA",
      maxAccounts: 80,
      hourlyCost: 21,
      commissionPct: 8,
      qaScore: 79,
      startedAt: "2026-06-10",
    }),
    agent({
      id: "ag_jordan",
      name: "Jordan Hale",
      role: "Floor lead",
      initials: "JH",
      status: "available",
      callsToday: 9,
      collectedToday: 420,
      clockedInAt: "2026-09-07T12:10:00.000Z",
      employment: "w2",
      remote: false,
      location: "Atlanta, GA",
      maxAccounts: 200,
      hourlyCost: 34,
      commissionPct: 4,
      qaScore: 96,
      startedAt: "2026-05-01",
    }),
    agent({
      id: "ag_priya",
      name: "Priya Shah",
      role: "Compliance",
      initials: "PS",
      status: "break",
      callsToday: 0,
      collectedToday: 0,
      clockedInAt: "2026-09-07T13:30:00.000Z",
      employment: "w2",
      remote: true,
      location: "Raleigh, NC",
      maxAccounts: 200,
      hourlyCost: 46,
      commissionPct: 0,
      qaScore: 100,
      startedAt: "2026-05-01",
    }),
  ];

  const portfolios: Portfolio[] = [
    {
      id: "pf_harborpoint",
      name: "Harborpoint PL Forward Flow Sep",
      seller: "Harborpoint Consumer Finance",
      assetClass: "Personal loan · fresh charge-off",
      purchasedAt: "2026-08-20",
      faceValue: 1_840_000,
      purchasePrice: 147_200,
      accountCount: 612,
      putbackUntil: "2026-11-18",
      mediaComplete: true,
      notes: "8 cents. Forward flow, monthly tranche. Media delivered with the tape.",
    },
    {
      id: "pf_accu",
      name: "ACCU Auto Deficiency 2026-A",
      seller: "Atlantic Coast Credit Union",
      assetClass: "Auto deficiency",
      purchasedAt: "2026-08-28",
      faceValue: 2_410_000,
      purchasePrice: 108_450,
      accountCount: 388,
      putbackUntil: "2026-11-26",
      mediaComplete: false,
      notes: "4.5 cents. Repossession docs outstanding on ~60 accounts — putback candidates.",
    },
    {
      id: "pf_summit",
      name: "Summit BNPL Charge-off 26B",
      seller: "Summit Consumer Lending",
      assetClass: "BNPL / small balance",
      purchasedAt: "2026-09-01",
      faceValue: 310_000,
      purchasePrice: 9_300,
      accountCount: 740,
      putbackUntil: "2026-12-01",
      mediaComplete: true,
      notes: "3 cents. Small balances — portal and SMS first, human calls only on RPC.",
    },
    {
      id: "pf_fhb",
      name: "FHB CC Primary Q3-26",
      seller: "First Horizon Bank",
      assetClass: "Credit card · primary placement",
      purchasedAt: "2026-09-03",
      faceValue: 960_000,
      purchasePrice: 0,
      accountCount: 214,
      putbackUntil: "2027-03-03",
      mediaComplete: true,
      notes: "Contingency placement, not a purchase. 28% contingency fee, no cost basis.",
    },
    {
      id: "pf_gulfshore",
      name: "Gulfshore Self-Pay (consumer placed)",
      seller: "Gulfshore Health System",
      assetClass: "Medical self-pay",
      purchasedAt: "2026-08-15",
      faceValue: 148_000,
      purchasePrice: 0,
      accountCount: 96,
      putbackUntil: "2027-02-15",
      mediaComplete: false,
      notes: "Contingency at 22%. Itemization required before any demand.",
    },
    {
      id: "pf_held",
      name: "Held — licensed state overflow",
      seller: "Mixed",
      assetClass: "Blended",
      purchasedAt: "2026-09-01",
      faceValue: 84_000,
      purchasePrice: 3_360,
      accountCount: 31,
      putbackUntil: "2026-12-01",
      mediaComplete: true,
      notes: "Accounts that landed in licensed states. Parked until licensure or resale.",
    },
  ];

  const accounts: Account[] = [
    acc({
      id: "ac_ga_1",
      firstName: "Marisol",
      lastName: "Bennett",
      phone: "(404) 555-0142",
      email: "m.bennett.demo@example.com",
      address: "184 Piedmont Ave",
      city: "Atlanta",
      state: "GA",
      zip: "30308",
      timezone: "America/New_York",
      last4: "4412",
      originalCreditor: "Harborpoint Consumer Finance",
      portfolio: "Harborpoint PL Forward Flow Sep",
      product: "Personal loan",
      chargeOff: "2026-03-12",
      placedAt: "2026-08-20",
      balance: 2840,
      original: 3100,
      status: "working",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 72,
      social: [
        { network: "facebook", handle: "public profile match · Atlanta", confidence: 68, note: "City + last name only. Do not friend." },
        { network: "linkedin", handle: "Not found", confidence: 12, note: "No confident professional match." },
      ],
      skipHits: [
        { id: "sk1", kind: "phone", value: "(404) 555-0177", confidence: 71, source: "Lexis-class header" },
        { id: "sk2", kind: "employer", value: "Dekalb logistics (possible)", confidence: 44, source: "credit header" },
      ],
      notes: "Asked about a $75 biweekly. Wants Friday payday.",
      portfolioId: "pf_harborpoint",
      disposition: "active",
      collected: 260,
    }),
    acc({
      id: "ac_ky_1",
      firstName: "Ellis",
      lastName: "Crowder",
      phone: "(502) 555-0119",
      email: "ellis.crowder.demo@example.com",
      address: "90 Story Ave",
      city: "Louisville",
      state: "KY",
      zip: "40206",
      timezone: "America/New_York",
      last4: "9031",
      originalCreditor: "Atlantic Coast Credit Union",
      portfolio: "ACCU Auto Deficiency 2026-A",
      product: "Auto deficiency",
      chargeOff: "2025-11-02",
      placedAt: "2026-08-28",
      balance: 6120,
      original: 6400,
      status: "validation_sent",
      language: "en",
      consent: { voice: true, sms: false, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: false,
      score: 54,
      social: [{ network: "nextdoor", handle: "No match", confidence: 8, note: "Skip only — no social outreach." }],
      skipHits: [],
      notes: "Left VM. No SMS consent.",
      portfolioId: "pf_accu",
      disposition: "active",
      collected: 0,
    }),
    acc({
      id: "ac_sc_1",
      firstName: "Tasha",
      lastName: "Ingram",
      phone: "(843) 555-0164",
      email: "tasha.ingram.demo@example.com",
      address: "22 King St",
      city: "Charleston",
      state: "SC",
      zip: "29401",
      timezone: "America/New_York",
      last4: "2288",
      originalCreditor: "Summit Consumer Lending",
      portfolio: "Summit BNPL Charge-off 26B",
      product: "BNPL",
      chargeOff: "2026-01-18",
      placedAt: "2026-09-01",
      balance: 418,
      original: 460,
      status: "ptp",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 81,
      social: [],
      skipHits: [],
      notes: "PTP $100 on the 12th. Card on file ending 4419.",
      portfolioId: "pf_summit",
      disposition: "active",
      collected: 42,
    }),
    acc({
      id: "ac_mo_1",
      firstName: "Hank",
      lastName: "Voss",
      phone: "(314) 555-0183",
      email: "hank.voss.demo@example.com",
      address: "4100 Gravois",
      city: "St. Louis",
      state: "MO",
      zip: "63116",
      timezone: "America/Chicago",
      last4: "7720",
      originalCreditor: "First Horizon Bank",
      portfolio: "FHB CC Primary Q3-26",
      product: "Credit card",
      chargeOff: "2026-04-09",
      placedAt: "2026-09-03",
      balance: 1940,
      original: 2100,
      status: "new",
      language: "en",
      consent: { voice: true, sms: true, email: false, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: false,
      miniMiranda: false,
      score: 61,
      social: [],
      skipHits: [],
      notes: "Validation not yet mailed. Bot should send before first demand.",
      portfolioId: "pf_fhb",
      disposition: "active",
      collected: 0,
    }),
    acc({
      id: "ac_ms_1",
      firstName: "Keisha",
      lastName: "Alston",
      phone: "(601) 555-0106",
      email: "keisha.alston.demo@example.com",
      address: "7 Farish St",
      city: "Jackson",
      state: "MS",
      zip: "39201",
      timezone: "America/Chicago",
      last4: "1194",
      originalCreditor: "Gulfshore Health System",
      portfolio: "Gulfshore Self-Pay (consumer placed)",
      product: "Medical self-pay",
      chargeOff: "2024-09-01",
      placedAt: "2026-08-15",
      balance: 880,
      original: 1200,
      status: "dispute",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 40,
      social: [],
      skipHits: [],
      notes: "Verbal dispute 9/4. Hold collections. Itemization requested.",
      portfolioId: "pf_gulfshore",
      disposition: "disputed",
      collected: 320,
    }),
    acc({
      id: "ac_oh_1",
      firstName: "Noah",
      lastName: "Pellegrino",
      phone: "(216) 555-0135",
      email: "noah.p.demo@example.com",
      address: "1200 W 6th",
      city: "Cleveland",
      state: "OH",
      zip: "44113",
      timezone: "America/New_York",
      last4: "5502",
      originalCreditor: "Harborpoint Consumer Finance",
      portfolio: "Harborpoint PL Forward Flow Sep",
      product: "Personal loan",
      chargeOff: "2025-12-20",
      placedAt: "2026-08-22",
      balance: 3560,
      original: 3900,
      status: "working",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      nextCallAfter: "2026-09-08T15:00:00.000Z",
      score: 66,
      social: [
        { network: "linkedin", handle: "possible warehouse supervisor · Cuyahoga", confidence: 39, note: "Low confidence. Do not message." },
      ],
      skipHits: [{ id: "sk3", kind: "phone", value: "(440) 555-0190", confidence: 63, source: "utilities header" }],
      notes: "Third no-contact. Skip recommended.",
      portfolioId: "pf_harborpoint",
      disposition: "active",
      collected: 340,
    }),
    acc({
      id: "ac_ca_block",
      firstName: "Riley",
      lastName: "Nguyen",
      phone: "(415) 555-0120",
      email: "riley.nguyen.demo@example.com",
      address: "88 Mission",
      city: "San Francisco",
      state: "CA",
      zip: "94105",
      timezone: "America/Los_Angeles",
      last4: "8801",
      originalCreditor: "Summit Consumer Lending",
      portfolio: "Held — licensed state",
      product: "Personal loan",
      chargeOff: "2026-02-01",
      placedAt: "2026-09-01",
      balance: 2400,
      original: 2400,
      status: "hold",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: false,
      miniMiranda: false,
      score: 50,
      social: [],
      skipHits: [],
      notes: "California — DFPI license required. Dialer will refuse.",
      portfolioId: "pf_held",
      disposition: "active",
      collected: 0,
    }),
    acc({
      id: "ac_ok_1",
      firstName: "Jade",
      lastName: "Harjo",
      phone: "(405) 555-0171",
      email: "jade.harjo.demo@example.com",
      address: "15 Western Ave",
      city: "Oklahoma City",
      state: "OK",
      zip: "73102",
      timezone: "America/Chicago",
      last4: "3340",
      originalCreditor: "Atlantic Coast Credit Union",
      portfolio: "ACCU Auto Deficiency 2026-A",
      product: "Auto deficiency",
      chargeOff: "2026-05-14",
      placedAt: "2026-09-02",
      balance: 4780,
      original: 5100,
      status: "plan",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 77,
      social: [],
      skipHits: [],
      notes: "Active $200 monthly ACH plan.",
      portfolioId: "pf_accu",
      disposition: "active",
      collected: 320,
    }),
    acc({
      id: "ac_ks_bk",
      firstName: "Roland",
      lastName: "Vestry",
      phone: "(316) 555-0122",
      email: "r.vestry.demo@example.com",
      address: "808 Douglas Ave",
      city: "Wichita",
      state: "KS",
      zip: "67202",
      timezone: "America/Chicago",
      last4: "6617",
      originalCreditor: "Harborpoint Consumer Finance",
      portfolio: "Harborpoint PL Forward Flow Sep",
      product: "Personal loan",
      chargeOff: "2026-01-09",
      placedAt: "2026-08-20",
      balance: 4210,
      original: 4210,
      status: "hold",
      language: "en",
      consent: { voice: false, sms: false, email: false, recorded: true },
      dnc: true,
      cease: true,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 5,
      social: [],
      skipHits: [],
      notes: "Chapter 7 filed 9/2. Automatic stay. All outreach locked. Putback candidate.",
      portfolioId: "pf_harborpoint",
      disposition: "bankrupt",
      collected: 0,
    }),
    acc({
      id: "ac_mt_dec",
      firstName: "Eileen",
      lastName: "Dorsey",
      phone: "(406) 555-0138",
      email: "e.dorsey.demo@example.com",
      address: "412 Last Chance Gulch",
      city: "Helena",
      state: "MT",
      zip: "59601",
      timezone: "America/Denver",
      last4: "2091",
      originalCreditor: "Atlantic Coast Credit Union",
      portfolio: "ACCU Auto Deficiency 2026-A",
      product: "Auto deficiency",
      chargeOff: "2025-10-16",
      placedAt: "2026-08-28",
      balance: 7340,
      original: 7340,
      status: "hold",
      language: "en",
      consent: { voice: false, sms: false, email: false, recorded: true },
      dnc: true,
      cease: true,
      timeBarred: false,
      validationSent: false,
      miniMiranda: false,
      score: 0,
      social: [],
      skipHits: [],
      notes: "Deceased — SSA death index match confirmed by skip vendor. No estate. Putback filed.",
      portfolioId: "pf_accu",
      disposition: "deceased",
      collected: 0,
    }),
    acc({
      id: "ac_sd_ref",
      firstName: "Brett",
      lastName: "Kohler",
      phone: "(605) 555-0159",
      email: "b.kohler.demo@example.com",
      address: "77 Phillips Ave",
      city: "Sioux Falls",
      state: "SD",
      zip: "57104",
      timezone: "America/Chicago",
      last4: "4480",
      originalCreditor: "Summit Consumer Lending",
      portfolio: "Summit BNPL Charge-off 26B",
      product: "BNPL",
      chargeOff: "2026-02-27",
      placedAt: "2026-09-01",
      balance: 610,
      original: 610,
      status: "cease",
      language: "en",
      consent: { voice: false, sms: false, email: false, recorded: true },
      dnc: false,
      cease: true,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 8,
      social: [],
      skipHits: [],
      notes: "Written refusal to pay plus cease request received 9/6. Closed to outreach.",
      portfolioId: "pf_summit",
      disposition: "refusal",
      collected: 0,
    }),
    acc({
      id: "ac_va_paid",
      firstName: "Nadia",
      lastName: "Ferrell",
      phone: "(804) 555-0147",
      email: "n.ferrell.demo@example.com",
      address: "210 E Cary St",
      city: "Richmond",
      state: "VA",
      zip: "23219",
      timezone: "America/New_York",
      last4: "8853",
      originalCreditor: "Harborpoint Consumer Finance",
      portfolio: "Harborpoint PL Forward Flow Sep",
      product: "Personal loan",
      chargeOff: "2026-03-02",
      placedAt: "2026-08-20",
      balance: 0,
      original: 1180,
      status: "paid",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 100,
      social: [],
      skipHits: [],
      notes: "Paid in full through the TF Recovery portal. Zero-balance letter sent.",
      portfolioId: "pf_harborpoint",
      disposition: "paid",
      collected: 1180,
    }),
    acc({
      id: "ac_nh_settled",
      firstName: "Gus",
      lastName: "Lindqvist",
      phone: "(603) 555-0111",
      email: "g.lindqvist.demo@example.com",
      address: "19 Elm St",
      city: "Manchester",
      state: "NH",
      zip: "03101",
      timezone: "America/New_York",
      last4: "3307",
      originalCreditor: "Summit Consumer Lending",
      portfolio: "Summit BNPL Charge-off 26B",
      product: "BNPL",
      chargeOff: "2026-04-18",
      placedAt: "2026-09-01",
      balance: 0,
      original: 540,
      status: "paid",
      language: "en",
      consent: { voice: true, sms: true, email: true, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: true,
      miniMiranda: true,
      score: 100,
      social: [],
      skipHits: [],
      notes: "Settled at 60% via SMS pay link. Settled-in-full letter on file.",
      portfolioId: "pf_summit",
      disposition: "settled",
      collected: 324,
    }),
    acc({
      id: "ac_ut_utl",
      firstName: "Priscilla",
      lastName: "Adeyemi",
      phone: "(801) 555-0166",
      email: "p.adeyemi.demo@example.com",
      address: "Unknown — mail returned",
      city: "Provo",
      state: "UT",
      zip: "84601",
      timezone: "America/Denver",
      last4: "7742",
      originalCreditor: "First Horizon Bank",
      portfolio: "FHB CC Primary Q3-26",
      product: "Credit card",
      chargeOff: "2026-02-14",
      placedAt: "2026-09-03",
      balance: 2260,
      original: 2260,
      status: "working",
      language: "en",
      consent: { voice: true, sms: false, email: false, recorded: true },
      dnc: false,
      cease: false,
      timeBarred: false,
      validationSent: false,
      miniMiranda: false,
      score: 22,
      social: [],
      skipHits: [],
      notes: "Validation returned undeliverable. Two skip passes, no new address. Needs a deeper trace.",
      portfolioId: "pf_fhb",
      disposition: "unable_to_locate",
      collected: 0,
    }),
  ];

  const plans: PaymentPlan[] = [
    {
      id: "pl_1",
      accountId: "ac_ok_1",
      installment: 200,
      remaining: 5,
      cadence: "monthly",
      nextDue: "2026-10-02",
      method: "ach",
      status: "active",
    },
    {
      id: "pl_2",
      accountId: "ac_sc_1",
      installment: 100,
      remaining: 4,
      cadence: "monthly",
      nextDue: "2026-09-12",
      method: "card",
      status: "active",
    },
  ];

  const payments: Payment[] = [
    {
      id: "py_1",
      accountId: "ac_ok_1",
      amount: 200,
      method: "ach",
      at: "2026-09-02T16:10:00.000Z",
      last4: "1182",
      status: "approved",
      channel: "recurring",
      descriptor: "TF RECOVERY",
      processorRef: "rp_8841002",
    },
    {
      id: "py_2",
      accountId: "ac_ga_1",
      amount: 75,
      method: "card",
      at: "2026-09-05T18:22:00.000Z",
      last4: "4419",
      status: "approved",
      channel: "agent",
      descriptor: "TF RECOVERY",
      processorRef: "rp_8841119",
    },
    {
      id: "py_3",
      accountId: "ac_va_paid",
      amount: 1180,
      method: "card",
      at: "2026-09-04T21:40:00.000Z",
      last4: "0042",
      status: "approved",
      channel: "portal",
      descriptor: "TF RECOVERY",
      processorRef: "rp_8840771",
    },
    {
      id: "py_4",
      accountId: "ac_nh_settled",
      amount: 324,
      method: "card",
      at: "2026-09-06T15:12:00.000Z",
      last4: "5519",
      status: "approved",
      channel: "sms",
      descriptor: "TF RECOVERY",
      processorRef: "rp_8841240",
    },
  ];

  const grants: AccessGrant[] = [
    {
      id: "gr_sam",
      agentId: "ag_sam",
      accountIds: ["ac_ga_1", "ac_oh_1", "ac_sc_1"],
      portfolioId: "pf_harborpoint",
      startsAt: "2026-09-07T13:00:00.000Z",
      expiresAt: "2026-09-07T21:00:00.000Z",
      reason: "Shift lease — Harborpoint fresh tier",
      grantedBy: "Jordan Hale",
    },
    {
      id: "gr_casey",
      agentId: "ag_casey",
      accountIds: ["ac_ky_1", "ac_mo_1", "ac_ok_1"],
      portfolioId: "pf_accu",
      startsAt: "2026-09-07T12:45:00.000Z",
      expiresAt: "2026-09-07T20:45:00.000Z",
      reason: "Shift lease — ACCU auto deficiency",
      grantedBy: "Jordan Hale",
    },
    {
      id: "gr_devon",
      agentId: "ag_devon",
      accountIds: ["ac_ut_utl"],
      startsAt: "2026-09-06T13:00:00.000Z",
      expiresAt: "2026-09-06T21:00:00.000Z",
      reason: "Expired — skip follow-up batch",
      grantedBy: "Jordan Hale",
    },
  ];

  const reviews: CallReview[] = [
    {
      id: "qa_1",
      accountId: "ac_ga_1",
      agentId: "ag_sam",
      at: "2026-09-05T18:15:00.000Z",
      durationSec: 252,
      transcript:
        "agent: Hi, am I speaking with Marisol? This is Sam with TF Recovery on a recorded line. This is an attempt to collect a debt and any information obtained will be used for that purpose. This communication is from a debt collector.\nconsumer: Yes, this is her.\nagent: Thanks. I have the Harborpoint personal loan ending 4412. Is now an okay time?\nconsumer: A couple minutes.\nagent: Appreciate it. Would seventy five every other Friday work, starting your next payday?\nconsumer: That could work.",
      score: 100,
      verdict: "pass",
      findings: [],
      coaching:
        "Sam, clean call. Score 100. Disclosures landed in the first fifteen seconds and you gave the consumer room to answer. Keep that pacing.",
      acknowledged: true,
    },
    {
      id: "qa_2",
      accountId: "ac_ms_1",
      agentId: "ag_casey",
      at: "2026-09-04T16:44:00.000Z",
      durationSec: 188,
      transcript:
        "agent: Is this Keisha? Casey calling about a balance of eight hundred eighty dollars.\nconsumer: Who is this?\nagent: We can keep calling until this is resolved, or you have to pay today and we close it out.\nconsumer: I dispute this, I never got a bill.\nagent: Fine, I will note it.",
      score: 30,
      verdict: "fail",
      findings: [
        {
          rule: "FDCPA 807(11) — mini-Miranda",
          severity: "critical",
          detail: "First contact must state this is an attempt to collect a debt from a debt collector.",
        },
        {
          rule: "Recording disclosure",
          severity: "major",
          detail: "Two-party consent states require an explicit recording notice before substance.",
        },
        {
          rule: "Time-barred revival risk",
          severity: "major",
          detail:
            "On out-of-statute paper, a demand for payment can restart the clock in some states. Disclose, do not demand.",
          quote: "We can keep calling until this is resolved, or you have to pay today and we close it out.",
        },
        {
          rule: "Reg F 1006.14(b) — call frequency pressure",
          severity: "minor",
          detail: "Avoid implying you will keep calling until they pay.",
          quote: "We can keep calling until this is resolved, or you have to pay today and we close it out.",
        },
      ],
      coaching:
        "Casey, this call scored 30 out of one hundred. Stop and read this part. One issue is a hard violation. FDCPA 807(11) — mini-Miranda. First contact must state this is an attempt to collect a debt from a debt collector. Recording disclosure. Two-party consent states require an explicit recording notice before substance. Time-barred revival risk. On out-of-statute paper, a demand for payment can restart the clock in some states. Disclose, do not demand. Reg F 1006.14(b) — call frequency pressure. Avoid implying you will keep calling until they pay. Acknowledge this review before your next dial.",
      acknowledged: false,
    },
  ];

  const timeline: TimelineEvent[] = [
    {
      id: "tl_1",
      accountId: "ac_ga_1",
      channel: "call",
      title: "Right-party contact · 4m 12s",
      body: "Mini-Miranda delivered. Consumer asked for $75 biweekly starting Friday payday. Offered portal link.",
      at: "2026-09-05T18:10:00.000Z",
      actor: "Sam Ruiz",
      outcome: "RPC · soft PTP",
    },
    {
      id: "tl_2",
      accountId: "ac_ga_1",
      channel: "payment",
      title: "Card payment $75",
      body: "Visa •4419 authorized. Balance 2,840.",
      at: "2026-09-05T18:22:00.000Z",
      actor: "Cove Pay",
      outcome: "approved",
    },
    {
      id: "tl_3",
      accountId: "ac_ga_1",
      channel: "sms",
      title: "Authenticated SMS (10DLC)",
      body: "This is a debt collector. Confirmation: $75 received. Reply STOP to opt out.",
      at: "2026-09-05T18:24:00.000Z",
      actor: "SMS agent",
      outcome: "delivered",
    },
    {
      id: "tl_4",
      accountId: "ac_mo_1",
      channel: "system",
      title: "Account placed",
      body: "FHB CC primary. Missouri — no state license. Validation not sent.",
      at: "2026-09-03T14:00:00.000Z",
      actor: "Cove",
    },
    {
      id: "tl_5",
      accountId: "ac_ms_1",
      channel: "call",
      title: "Verbal dispute",
      body: "Consumer disputes amount and asked for itemization. Collections paused.",
      at: "2026-09-04T16:40:00.000Z",
      actor: "Casey Quinn",
      outcome: "dispute",
    },
    {
      id: "tl_6",
      accountId: "ac_oh_1",
      channel: "call",
      title: "No contact · 3rd attempt",
      body: "Ring-no-answer. Cool-down set. Skip recommended.",
      at: "2026-09-06T19:05:00.000Z",
      actor: "Voice agent v3",
      outcome: "no_contact",
    },
    {
      id: "tl_7",
      accountId: "ac_sc_1",
      channel: "email",
      title: "Authenticated email (DMARC pass)",
      body: "PTP reminder for $100 on Sep 12. Mini-Miranda in footer.",
      at: "2026-09-06T12:00:00.000Z",
      actor: "Email agent",
      outcome: "opened",
    },
    {
      id: "tl_8",
      accountId: "ac_ca_block",
      channel: "system",
      title: "Hold — licensed state",
      body: "California DFPI license required. Outbound channels locked.",
      at: "2026-09-01T15:00:00.000Z",
      actor: "State gate",
    },
  ];

  const scripts: ScriptVersion[] = [
    {
      id: "sc_1",
      version: 1,
      body: "Hello, may I speak with {{name}}? This is {{agent}} calling from Cove Recovery on a recorded line. This is an attempt to collect a debt…",
      createdAt: "2026-08-01",
      reason: "Initial compliance script",
      rpcRate: 0.18,
      ptpRate: 0.07,
      complaintRate: 0.012,
      naturalness: 0.54,
    },
    {
      id: "sc_2",
      version: 2,
      body: "Hi — looking for {{name}}. I’m {{agent}} with Cove Recovery. I’ll keep this short. This is an attempt to collect a debt, and anything you share is used for that. I have the Harborpoint personal loan ending {{last4}}…",
      createdAt: "2026-08-20",
      reason: "Less stacked disclosures up front; same mini-Miranda, more breath.",
      rpcRate: 0.23,
      ptpRate: 0.11,
      complaintRate: 0.009,
      naturalness: 0.71,
    },
    {
      id: "sc_3",
      version: 3,
      body: "Hey {{name}}? {{agent}} at Cove Recovery, recorded line. I’m a debt collector — this is an attempt to collect a debt. I can take card or ACH, or a Friday payday plan if that’s easier. What’s a number that works this week?",
      createdAt: "2026-09-04",
      reason: "Self-improve: v2 dropped after “I have the account” too fast. Offer a path before reciting balance.",
      rpcRate: 0.27,
      ptpRate: 0.14,
      complaintRate: 0.008,
      naturalness: 0.8,
    },
  ];

  return {
    agents,
    accounts,
    portfolios,
    plans,
    payments,
    timeline,
    scripts,
    queue: [],
    messages: [],
    templates: TEMPLATES,
    grants,
    reviews,
    liveCall: null,
    currentAgentId: null,
    autoBot: false,
  };
}
