import type { WorkspaceConfig, WorkspaceId } from "./types";

export const WORKSPACES: Record<WorkspaceId, WorkspaceConfig> = {
  triton: {
    id: "triton",
    name: "Triton",
    legalName: "Triton Financial Solutions, LLC",
    product: "DebtMarket",
    domain: "debtmarket.net",
    email: "portfolios@debtmarket.net",
    phone: "+1 (561) 254-6608",
    city: "Coconut Creek, FL",
    industry: "Charged-off receivables brokerage",
    tagline: "Institutional marketplace for charged-off consumer and commercial debt portfolios.",
    theme: {
      accent: "#c9a24a",
      accentSoft: "rgba(201, 162, 74, 0.16)",
      accentText: "#7d5f14",
      accentTextDark: "#e6cd8e",
      mark: "TF",
      hero: "linear-gradient(135deg, #0c1620 0%, #1b3348 55%, #c9a24a 160%)",
    },
    dealNoun: "portfolio trade",
    dealNounPlural: "portfolio trades",
    inventoryNoun: "portfolio",
    inventoryNounPlural: "portfolios",
    pipeline: [
      "Seller intake",
      "NDA executed",
      "Data room live",
      "Bid window",
      "Award",
      "Funding & close",
      "Post-sale media",
    ],
    inventoryKinds: [
      "Credit card charge-off",
      "Auto deficiency",
      "Medical receivables",
      "Personal loans",
      "Telecom",
      "Private student loans",
      "Commercial paper",
      "Fintech specialty",
    ],
    complianceBadges: ["FDCPA-aware", "RMAI-aligned", "Institutional only", "No consumer contact"],
  },
  aether: {
    id: "aether",
    name: "Aether",
    legalName: "Aether Digital Markets",
    product: "Aether Desk",
    domain: "aethermarkets.io",
    email: "desk@aethermarkets.io",
    phone: "+1 (415) 555-0148",
    city: "New York, NY",
    industry: "Institutional crypto markets",
    tagline: "OTC, listings, custody introductions, and market-making coverage for digital assets.",
    theme: {
      accent: "#5eead4",
      accentSoft: "rgba(94, 234, 212, 0.16)",
      accentText: "#0d6d66",
      accentTextDark: "#8ff3e3",
      mark: "AE",
      hero: "linear-gradient(135deg, #070d13 0%, #12263a 50%, #5eead4 155%)",
    },
    dealNoun: "desk mandate",
    dealNounPlural: "desk mandates",
    inventoryNoun: "listing / block",
    inventoryNounPlural: "listings & blocks",
    pipeline: [
      "RFQ received",
      "Indicative",
      "Firm quote",
      "Allocated",
      "On-chain settle",
      "Custody booked",
      "Post-trade",
    ],
    inventoryKinds: [
      "BTC / ETH block",
      "Altcoin OTC",
      "Token listing",
      "Market-making mandate",
      "Custody onboarding",
      "Treasury conversion",
      "Options / structured",
      "Fund allocation",
    ],
    complianceBadges: ["KYC/AML", "Travel Rule", "Qualified custody", "Institutional only"],
  },
};

export function workspaceOf(id: WorkspaceId): WorkspaceConfig {
  return WORKSPACES[id];
}
